### PR TITLE
added qqq pot and pt_BR

### PR DESCRIPTION
**Pull request by patogit**
I added the qqq lang code (for message documentation for translators), pt_BR, and a translation template file called django.pot (the latter might be totally unnecessary). I don't know if the way I did it is correct, since I'm note sure how the script works that collects the strings. Also, I notice that in the Spanish django.po file, there are a number of strings at the end of the file that are commented out... What's that about?

### CODE REVIEW

**Comment by ilario** [comment]
Looks great but please notice that we have a complete rewrite of Chef here: https://github.com/libremesh/chef

This means that we stopped developing this repository and the active one now is the other one (I specified this in the description of this repository, I'm going to add this info also in the readme).

**Comment by patogit** [comment]
Ok. The new Chef seems to be monolingual (English), with all the interface messages hard-coded in chef.html. Do you have any ideas about how we can internationalize this, in order to make easy translation possible? The first ideas that come to my mind are:

1) Find a way to replace the interface strings in the HTML file with keys that are rendered from a translation file, like LimeApp does at https://github.com/libremesh/lime-app/tree/uhttpd/i18n/translations. Then figure out when those pages get rendered, and how the user chooses their language.

...or...

2) Create a parser-generator in PHP (this would run on TranslateWiki.net) that pulls out the interface strings from that file (making them available to translate on TW.net) and then writes the translated strings to a new files, such as chef-es.html for Spanish. Then we'd have to put an option somewhere on the interface to switch between languages.

In the end, those two options are pretty similar to each other in terms of the work required. Maybe we can get better ideas from other software.

**Comment by patogit** [comment]
Right now it has fewer than 10 strings, so another option is to just translate by hand for a few languages. That still leaves the question: How do we let the user know that there are multiple languages available, and switch between them?

**Comment by patogit** [comment]
Also, once Chef is available in Spanish, will it be able to cook firmware that gives my router an interface in Spanish?

In other words, I choose Spanish for the interface for Chef (or my browser automatically sends me to the Spanish version), I cook some firmware, I flash that firmware onto a router and reboot it, I login to the router, and the LibreMesh/LuCI interface is in Spanish... one seamless experience.

**Comment by ilario** [comment]
They are all very good points, I moved the discussion on libremesh/chef#19

**Comment by nicopace** [comment]
This is not needed anymore as this piece of software is obsolete. Closing the issue.

**Pull request closed without merging**
